parameters:
  atolye15_slack_exception.listener_class: Atolye15\SlackExceptionBundle\EventListener\ExceptionListener
  atolye15_slack_exception.post_service_class: Atolye15\SlackExceptionBundle\Service\PostService

services:
  atolye15_slack_exception.listener:
    class: "%atolye15_slack_exception.listener_class%"
    arguments:
      container: "@service_container"
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  atolye15_slack_exception.post_service:
    class: "%atolye15_slack_exception.post_service_class%"
    arguments:
      container: "@service_container"
      tokenStorage: "@security.token_storage"
